version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyna_backend
    ports:
      - "3007:3000" # Map 3007 sur l'hôte vers 3000 dans le conteneur
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=cyna_database
      - DB_PORT=3306 # Port interne MySQL
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: cyna_db
    ports:
      - "3307:3306" # Map 3307 sur l'hôte vers 3306 dans le conteneur
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: cyna_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
