
services:

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app

    volumes:
      - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on: 
      - db

  api:
    image: node:22.14  #Version Node
    volumes:
      - ".:/app"  #Initialize l'application
    ports:
      - "3006:3006" #Port de connexion à l'application via serveur
      - "5577:5555" # command (npx prisma studio) to launch the prisma database access on port 5555
    command: npm run dev
    working_dir: /app
    depends_on:
      - db

volumes:
  dbdata:

# https://hub.docker.com/_/node
# docker compose up
# docker compose up -d
# docker ps -a
# docker compose exec <service_name> <path_to_executable> (docker compose exec app bash) --Commande fréquement utilisée
# docker ocmpose down
