version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyna_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=cyna_database
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: cyna_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: cyna_database
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
